### ISSUE TITLE
no Serial number is available on the shell page (only a ID is shown), not able to add it

### ISSUE THREAD

**Issue by AlexanderTurnowsky** [cyberjunky/home-assistant-shell_recharge#38]
### System Health details

-

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/cyberjunky/home-assistant-shell_recharge/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

i installed it via HACS. When trying to find the serial number of the charging station, this is not working as only a ID is shown, and this is not working.
https://shellrecharge.com/en-gb/find-a-charge-point 
I'm leaving in Austria maybe this is the problem that only ID's are shown?

### Reproduction steps

1. not able to add ID and no serial number is shown by shell
2.
3.
...

### Debug logs

```text
-
```

**Comment by cyberjunky** [comment]
@AlexanderTurnowsky can you show me (screenshot) or link to a charger which has this problem? It might be just a different naming... I know code that also fetched data using other ID formats, but I skipped it because the info I needed was already on the find charger site.

**Comment by ronbouwmeester** [comment]
I have the same issue's with some charge points, they used to work, but suddenly the serial number changed and cannot add the new one.
![NLQWCE2X4VM21](https://github.com/user-attachments/assets/85713dac-ebac-46f3-8004-0ee545aa9dac)

**Comment by cyberjunky** [comment]
Hi, can you try to delete the old entry, if still there and try again?
If this still fails please enable debug logging and share the debug log errors, if any.

I managed to add it without issues...

![image](https://github.com/user-attachments/assets/7cfd5f00-1c7b-41de-ab9a-ea5d9f147616)

**Comment by ronbouwmeester** [comment]
Hi, The first try was no success, but after updating from 0.1.7 to 0.1.8, it worked!
Thanks a lot!

![Succes](https://github.com/user-attachments/assets/8f13d5e9-f734-4099-ade6-3d598e252ab4)

**Comment by cyberjunky** [comment]
Closing because solved!

**Comment by AlexanderTurnowsky** [comment]
not sure how this is solved as for me this is not working, as there is no serial number only a serial ID. For this serial ID it is not working.

**Comment by cyberjunky** [comment]
@ronbouwmeester  had a slightly different issue.

If the shellrecharge website displays false info there isn't much I can do/fix.
The displayed 319 serial is also used at another station in Italy. How can two of them have the same serial?
![image](https://github.com/user-attachments/assets/bff1f027-a301-4ee9-a8fc-c05695dddb28)

When I look at the used json underneath the website, this data is used for the charger you posted:
https://route.eu.shellrecharge.com/api/chargepoint?id=3940189

I use the external id's only, I can see if I can add chargepoint id's but I do not known yet if these chargepoint id's are easy to find for end users.
Shell Recharge bought several companies all using different id format, hence the external ID format is there.

Maybe there are other integrations using that id instead, I haven't look recently
