### ISSUE TITLE
Home charging - Public sharing disabled

### ISSUE THREAD

**Issue by fvhemert** [cyberjunky/home-assistant-shell_recharge#43]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/cyberjunky/home-assistant-shell_recharge/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No, I do not believe this is a problem, i guess private charges are not (yet) implemented.

### Describe the solution you'd like

When trying to create a device for my private charging station (8 digit serial number, marked as "Public sharing disabled") the following error message is generated: "Empty reponse from shellrecharge.com. Either invalid SERIAL-NUMBER or no data found for it."
I would like to add my own charger to HA if possible.

### Describe alternatives you've considered

Do not see any alternatives

### Additional context

I would love to see the actual energy consumption when in use so I can incorporate it in the energy dashboard

**Comment by fvhemert** [comment]
Hi Ron, thanks for getting back to me. I tried the URL you have provided. If a public serial is no is used it returns relevant information about the public charge point, when trying the same with a private serial number, there is no error message, just an empty page.

It would be very nice to access the charge point directly but that will not work. The charge point has its own data connection using a built in (GSM) radio and connects directly to its backend. As far as I know it does not expose its information publicly.

Would love to understand if there is some kind of API available.

**Comment by cyberjunky** [comment]
@fvhemert depends on what the charger is that you are using I guess. Search on github for "python api <brand of charger>"

**Comment by cyberjunky** [comment]
I hope you can find an appropiate api package/ha integration, closing this ticket, since I cannot add the functionality asked.
