### ISSUE TITLE
broken link to issues and documentation

### ISSUE THREAD

**Issue by guidokieboom** [cyberjunky/home-assistant-shell_recharge#57]
## System Information

version | core-2024.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1411
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 22, 2024, 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
instance_id | b97ee5197eb040348268e734e9f8c589
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 219.4 GB
disk_used | 51.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.2), Mosquitto broker (6.4.1), Terminal & SSH (9.14.0), MariaDB (2.7.1), phpMyAdmin (0.9.1), Zigbee2MQTT (1.40.1-1), ESPHome (2024.8.1), AdGuard Home (5.1.2), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0), FTP (5.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 18
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 10, 2024, 11:02 AM
-- | --
current_recorder_run | September 18, 2024, 2:10 PM
estimated_db_size | 1695.16 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/cyberjunky/home-assistant-shell_recharge/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When clicking on issues or documentation, a end up in the Github 404 page. I guess due to a typo in the link (- instead of _)
<img width="226" alt="image" src="https://github.com/user-attachments/assets/50013730-5559-4a00-8316-2d73efeec402">

malfunctioning link: https://github.com/cyberjunky/home-assistant_shell_recharge/issues

correct link: https://github.com/cyberjunky/home-assistant-shell_recharge

### Reproduction steps

1. click on issues
2. click on documentation
3.
...

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by cyberjunky** [comment]
Fixed in version 0.1.10, thank you for reporting!
